# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('organizations', '0001_initial'),
        ('prisoners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSequence',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=24, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('status', models.CharField(choices=[('AWAITING_PRISONER', 'Ожидает подписи осуждённого'), ('PARTIALLY_SIGNED', 'Подписан частично'), ('ACTIVE', 'Действующий'), ('EXPIRED', 'Истёк')], default='AWAITING_PRISONER', max_length=24)),
                ('document', models.FileField(blank=True, upload_to='contracts/')),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('document_version', models.PositiveIntegerField(default=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='applications.jobapplication')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='applications.candidateproposal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.organization')),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='prisoners.prisoner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.CharField(choices=[('PRISONER', 'Осуждённый'), ('ENBEK_MANAGER', 'Руководитель Еңбек'), ('BUSINESS_ADMIN', 'МСБ')], max_length=24)),
                ('method', models.CharField(choices=[('BIOMETRY', 'Биометрия'), ('BUTTON', 'Подтверждение кнопкой')], max_length=16)),
                ('signed_at', models.DateTimeField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('signed_by', models.ForeignKey(help_text='Сотрудник, инициировавший биометрию, либо нажавший кнопку.', on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.employmentcontract')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricSignatureAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('verification_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('VERIFIED', 'Подтверждена'), ('FAILED', 'Не пройдена'), ('EXPIRED', 'Истекла')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_attempts', to='contracts.employmentcontract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='contractsignature',
            constraint=models.UniqueConstraint(fields=('contract', 'party'), name='unique_contract_party'),
        ),
    ]
