# Generated by Django 5.2.17 on 2026-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricsignatureattempt',
            name='contract_digest',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='biometricsignatureattempt',
            name='contract_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
