# Generated by Django 5.2.17 on 2026-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_biometricsignatureattempt_contract_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentcontract',
            name='organization_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
