# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИИН должен содержать 12 цифр')])),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='prisoners/reference/')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-rating', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ru', models.CharField(max_length=120, unique=True)),
                ('name_kk', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='PrisonerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners.prisoner')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prisoners.skill')),
            ],
        ),
        migrations.AddField(
            model_name='prisoner',
            name='skills',
            field=models.ManyToManyField(related_name='prisoners', through='prisoners.PrisonerSkill', to='prisoners.skill'),
        ),
        migrations.AddConstraint(
            model_name='prisonerskill',
            constraint=models.UniqueConstraint(fields=('prisoner', 'skill'), name='unique_prisoner_skill'),
        ),
    ]
