# Generated by Django 5.2.17 on 2026-09-22 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='criminal_article',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='current_employment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='disability_status',
            field=models.CharField(choices=[('NONE', 'Нет инвалидности'), ('GROUP_1', 'I группа'), ('GROUP_2', 'II группа'), ('GROUP_3', 'III группа')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='disciplinary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='health_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='medical_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='penitentiary_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='pension_status',
            field=models.CharField(choices=[('NONE', 'Не является пенсионером'), ('AGE', 'По возрасту'), ('DISABILITY', 'По инвалидности'), ('OTHER', 'Иное основание')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='pre_prison_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='pre_prison_experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='safety_briefing_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='sentence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='sentence_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='sentence_term',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='total_work_experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PrisonerChangeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('QUALIFICATION', 'Квалификация'), ('HEALTH', 'Состояние здоровья'), ('EMPLOYMENT', 'Трудовая занятость')], max_length=20)),
                ('effective_date', models.DateField()),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='prisoners.prisoner')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
