# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('prisoners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('skill_requirement', models.CharField(choices=[('REQUIRED', 'Только с навыком'), ('TRAINING_ALLOWED', 'Возможно обучение')], max_length=24)),
                ('workplace_address', models.CharField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_months', models.PositiveSmallIntegerField(default=12, editable=False)),
                ('schedule', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('FULL', 'Полная занятость'), ('PART_TIME', 'Частичная занятость')], max_length=16)),
                ('activity_description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Подана'), ('PROPOSED', 'Кандидаты предложены'), ('BUSINESS_RESPONDED', 'Ответ МСБ получен'), ('APPROVED', 'Согласована Еңбек'), ('REJECTED_BUSINESS', 'Отклонено по инициативе заявителя'), ('REJECTED_ENBEK', 'Отклонено по инициативе Еңбек'), ('SCREENING', 'Обследование'), ('CONTRACTING', 'Заключение договоров'), ('COMPLETED', 'Завершена'), ('WITHDRAWN', 'Отозвана')], default='DRAFT', max_length=32)),
                ('business_comment', models.TextField(blank=True)),
                ('enbek_comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='organizations.organization')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prisoners.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Предложен'), ('BUSINESS_ACCEPTED', 'Выбран МСБ'), ('BUSINESS_REJECTED', 'Не выбран МСБ'), ('ENBEK_APPROVED', 'Согласован Еңбек'), ('ENBEK_REJECTED', 'Отклонён Еңбек'), ('MEDICAL_PENDING', 'Ожидает медосмотр'), ('MEDICAL_PASSED', 'Медосмотр пройден'), ('MEDICAL_FAILED', 'Медицинский отказ'), ('PSYCHOLOGICAL_PENDING', 'Ожидает психолога'), ('PSYCHOLOGICAL_PASSED', 'Психолог пройден'), ('PSYCHOLOGICAL_FAILED', 'Отказ психолога'), ('READY_FOR_CONTRACT', 'Готов к договору'), ('CONTRACT_CREATED', 'Договор создан')], default='PROPOSED', max_length=32)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='prisoners.prisoner')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['-prisoner__rating', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('MEDICAL', 'Медицинское обследование'), ('PSYCHOLOGICAL', 'Психологическое обследование')], max_length=16)),
                ('result', models.CharField(choices=[('PENDING', 'Ожидает заключения'), ('APPROVED', 'Согласовано'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='applications.candidateproposal')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidateproposal',
            constraint=models.UniqueConstraint(fields=('application', 'prisoner'), name='unique_application_candidate'),
        ),
        migrations.AddConstraint(
            model_name='screening',
            constraint=models.UniqueConstraint(fields=('candidate', 'kind'), name='unique_candidate_screening'),
        ),
    ]
