# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OkedCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name_ru', models.CharField(max_length=500)),
                ('name_kk', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('BUSINESS', 'МСБ'), ('ENBEK', 'РГП Еңбек')], default='BUSINESS', max_length=16)),
                ('bin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'БИН должен содержать 12 цифр')])),
                ('activity_type', models.CharField(max_length=255)),
                ('staff_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('legal_address', models.CharField(max_length=500)),
                ('actual_address', models.CharField(max_length=500)),
                ('actual_address_same', models.BooleanField(default=False)),
                ('oked_code', models.CharField(max_length=16)),
                ('bank_details', models.TextField()),
                ('licenses', models.TextField(blank=True)),
                ('director_full_name', models.CharField(max_length=255)),
                ('director_iin', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИИН должен содержать 12 цифр')])),
                ('director_position', models.CharField(max_length=255)),
                ('director_email', models.EmailField(max_length=254)),
                ('director_phone', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
