# Generated by Django 5.2.17 on 2026-09-21 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bic', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{8}$', 'БИК должен содержать 8 символов')])),
                ('bank_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Код банка должен содержать 3 цифры')])),
                ('name_ru', models.CharField(max_length=500)),
                ('name_kk', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_ru'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='iik',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^KZ\\d{2}[A-HJ-NP-Z0-9]{16}$', 'ИИК должен быть казахстанским IBAN из 20 символов')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='kbe',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[12]\\d$', 'КБЕ должен содержать 2 цифры')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.bank'),
        ),
    ]
